export const products = [
  {
    image: "images/img1.png",
    name: "Zweiseitiger Wendemantel Mit Schmetterlingsxzds",
    colors: 6,
    price: 299.0,
    offPrice: 79.0,
  },
  {
    image: "images/img2.png",
    name: "Écharpe tisée avec bords contrastants et franges",
    colors: 17,
    price: 299.0,
    offPrice: 79.0,
  },
  {
    image: "images/img3.png",
    name: "Трикотажный Супер Мягкий Плед Контрастного Оттенка",
    colors: 6,
    price: 299.0,
    offPrice: 79.0,
  },
  {
    image: "images/img4.png",
    name: "Кардиган в Стиле Колор-Блок с V-Образным Воротником",
    colors: 6,
    price: 299.0,
    offPrice: 79.0,
  },
  {
    image: "images/img5.png",
    name: "Zweiseitiger Wendemantel Mit Schmetterlingsxzds",
    colors: 6,
    price: 299.0,
    offPrice: 79.0,
  },
  {
    image: "images/img6.png",
    name: "Écharpe tisée avec bords contrastants et franges",
    colors: 17,
    price: 299.0,
    offPrice: 79.0,
  },
  {
    image: "images/img7.png",
    name: "Трикотажный Супер Мягкий Плед Контрастного Оттенка",
    colors: 6,
    price: 299.0,
    offPrice: 79.0,
  },
  {
    image: "images/img8.png",
    name: "Кардиган в Стиле Колор-Блок с V-Образным Воротником",
    colors: 6,
    price: 299.0,
    offPrice: 79.0,
  },
];
